baseURL = "https://satyen3.github.io/"
languageCode = "en-us"
title = "Satyen Patel"
theme = "PaperMod"

[params]
  DateFormat = "January 2, 2006"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  defaultTheme = "light"
  disableThemeToggle = true
  ShowToc = false
  math = true
  hideSummary = true

[markup.goldmark.extensions.passthrough]
  enable = true

[markup.goldmark.extensions.passthrough.delimiters]
  block = [['$$', '$$'], ['\\[', '\\]']]
  inline = [['$', '$'], ['\\(', '\\)']]

[[menu.main]]
  identifier = "research"
  name = "Research"
  url = "/research/"
  weight = 10

[[menu.main]]
  identifier = "notes"
  name = "Notes"
  url = "/notes/"
  weight = 20

[[menu.main]]
  identifier = "reading"
  name = "Reading"
  weight = 30
  url = "/reading/"

[[menu.main]]
  identifier = "essays"
  name = "Essays"
  weight = 40
  url = "/essays/"

[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = "/cv.pdf"
  weight = 50
